image: alpine/latest
packages:
  - curl
sources:
  - https://git.sr.ht/~cofob/matrix-dnsbot
triggers:
  - action: email
    condition: failure
    to: failure@cofob.ru
tasks:
  - install: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y -q --default-toolchain nightly --profile minimal
  - check: |
      source $HOME/.cargo/env
      cd matrix-dnsbot
      cargo c
  - test: |
      source $HOME/.cargo/env
      cd matrix-dnsbot
      cargo test
