image: debian/bullseye
packages:
  - curl
  - openssl
  - libssl-dev
  - pkg-config
  - lld
  - gcc
  - upx
secrets:
  - 181a05d1-5754-4673-8ee0-f3c9e1be834d
sources:
  - https://git.sr.ht/~cofob/matrix-dnsbot
triggers:
  - action: email
    condition: failure
    to: failure@cofob.ru
artifacts:
  - matrix-dnsbot/dnsbot
  - matrix-dnsbot/dnsbot-upx
tasks:
  - install: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y -q --default-toolchain nightly --profile minimal
  # - check: |
  #     source $HOME/.cargo/env
  #     cd matrix-dnsbot
  #     cargo c
  # - test: |
  #     source $HOME/.cargo/env
  #     cd matrix-dnsbot
  #     cargo test
  - build: |
      source $HOME/.cargo/env
      cd matrix-dnsbot
      cargo build --release
      cp target/release/dnsbot dnsbot
  - compress: |
      cd matrix-dnsbot/
      upx -9 dnsbot -o dnsbot-upx
  - setup-docker: |
      curl -fsSL https://get.docker.com -o get-docker.sh
      sudo sh get-docker.sh
      sudo systemctl start docker
      sudo chmod 666 /var/run/docker.sock
      sudo usermod -aG docker ${USER}
      sleep 10
      cat ~/.docker_pass | docker login --username cofob --password-stdin
  - build-container: |
      cd matrix-dnsbot/
      sudo docker build -t dnsbot . --build-arg bin=dnsbot-upx
      sudo docker tag dnsbot cofob/dnsbot
      sudo docker image push cofob/dnsbot
